apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubecontrollermanagers.operator.openshift.io
spec:
  scope: Cluster
  group: operator.openshift.io
  version: v1
  names:
    kind: KubeControllerManager
    plural: kubecontrollermanagers
    singular: kubecontrollermanager
    categories:
    - coreoperators
  subresources:
    status: {}
