apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: openshift-kube-controller-manager
  name: kube-controller-manager
  labels:
    app: openshift-kube-controller-manager
    controller-manager: "true"
spec:
  upgradeStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: openshift-kube-controller-manager
      controller-manager: "true"
  template:
    metadata:
      name: openshift-kube-controller-manager
      labels:
        app: openshift-kube-controller-manager
        controller-manager: "true"
    spec:
      serviceAccountName: openshift-kube-controller-manager-sa
      containers:
      - name: controller-manager
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["hyperkube", "kube-controller-manager"]
        args:
        - "--openshift-config=/var/run/configmaps/config/config.yaml"
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/service-account-private-key
          name: service-account-private-key
        - mountPath: /var/run/secrets/cluster-signing-ca
          name: cluster-signing-ca
        - mountPath: /var/run/configmaps/client-ca
          name: client-ca
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: Exists
      volumes:
      - name: config
        configMap:
          name: deployment-kube-controller-manager-config
      - name: cluster-signing-ca
        secret:
          secretName: cluster-signing-ca
      - name: service-account-private-key
        secret:
          secretName: service-account-private-key
      - name: client-ca
        configMap:
          name: client-ca
      - name: serving-cert
        secret:
          secretName: serving-cert
